server:
  port: 28080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigc_database?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: mxz180426
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

## 小队api
api:
  bluelm:
    app-id: "3033936351"
    secret: "JCuXgJuLbtINqlYy"
## 初始api
#api:
#  bluelm:
#    app-id: "3031413662"
#    secret: "NSBeCiTewMNoLacx"

#file:
#  pic-dir: "C:\\Users\\12952\\Pictures\\AIGC\\picture\\"
#  vid-dir: "C:\\Users\\12952\\Pictures\\AIGC\\video\\"

file:
  pic-dir: "\\ssadmin-server\\source\\picture\\"
  vid-dir: "\\ssadmin-server\\source\\video\\"


#file:
#  pic-dir: C:\Users\12952\Pictures\AIGC\picture\
#  vid-dir: C:\Users\12952\Pictures\AIGC\video\



